export const TabOpened = "TabOpened"
export const OrderPlaced = "OrderPlaced"
export const FoodPrepared = "FoodPrepared"
export const FoodServed = "FoodServed"
export const DrinkServed = "DrinkServed"
export const OrderServed = "OrderServed"
export const TabClosed = "TabClosed"